# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2020 AAEON Technology Inc. - https://www.aaeon.com/

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
obj-y   += board_detect.o
